export const FETCH_USER = 'FETCH_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const STORE_USER_ERROR_MSG = 'STORE_USER_ERROR_MSG';
export const SET_PROFILE_IMAGE = 'SET_PROFILE_IMAGE';